### ISSUE TITLE
DB: relationele database opzetten

### ISSUE THREAD

**Issue by elementer23** [INF2-ICT/documentation#37]

**Comment by StefanMeijer** [comment]
https://newuniversity-my.sharepoint.com/:u:/r/personal/robin_van_dijk1_student_nhlstenden_com/Documents/Project_6.1/Projectbestanden(Databases%20etc.)/[quintor.sql](https://newuniversity-my.sharepoint.com/:u:/r/personal/robin_van_dijk1_student_nhlstenden_com/Documents/Project_6.1/Projectbestanden(Databases%20etc.)/quintor.sql?csf=1&web=1&e=Wob7bl)?csf=1&web=1&e=Wob7bl
